#!/usr/bin/env bash
set -euo pipefail

# Regenerates the parts of ~/.aerospace.toml that are derived from
# workspaces.conf and displays.conf: the persistent workspace list, the
# workspace-to-monitor assignment, and the Ctrl+N / Ctrl+Shift+N shortcuts.
#
# AeroSpace reads TOML and cannot read a shell config, so the two have to be
# kept in step by something. Doing it with a generator rather than by hand is
# what makes "change the number of workspaces" one edit instead of twenty-six
# shortcut lines plus six scripts.
#
# Only the marked blocks are touched. Everything else in the file - app rules,
# your own keybindings, your comments - is copied through untouched, so this is
# safe to run against a config you have edited. The previous file is backed up
# whenever the content actually changes.
#
# Usage:
#   render-layout.sh [--check] [path-to-aerospace.toml]
#
#   --check   report whether the file is up to date and change nothing.
#             Exit 0 when it matches, 1 when it would be rewritten.
#   --no-app-rules
#             do not re-render the app placement rules afterwards.

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=lib/layout.sh
source "$SCRIPT_DIR/lib/layout.sh"

LAYOUT_BEGIN='# >>> generated by render-layout.sh - workspaces and monitors >>>'
LAYOUT_END='# <<< generated by render-layout.sh - workspaces and monitors <<<'
KEYS_BEGIN='    # >>> generated by render-layout.sh - workspace keys >>>'
KEYS_END='    # <<< generated by render-layout.sh - workspace keys <<<'

usage() {
    cat <<'EOF'
usage: render-layout.sh [--check] [--no-app-rules] [path-to-aerospace.toml]

  --check          report drift and change nothing (exit 1 when out of date)
  --no-app-rules   skip re-rendering app placement rules afterwards
  -h               show this help

Reads ~/.config/aerospace/workspaces.conf and displays.conf.
EOF
}

check_only=0
render_app_rules=1
config_path=""

while [ "$#" -gt 0 ]; do
    case "$1" in
        --check)
            check_only=1
            ;;
        --no-app-rules)
            render_app_rules=0
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        -*)
            printf 'Unknown option: %s\n\n' "$1" >&2
            usage >&2
            exit 64
            ;;
        *)
            config_path="$1"
            ;;
    esac
    shift
done

config_path="${config_path:-$HOME/.aerospace.toml}"

if [ ! -f "$config_path" ]; then
    printf 'No AeroSpace config at %s\n' "$config_path" >&2
    exit 1
fi

aerospace_layout_load_config

# TOML literal strings cannot contain a single quote, so a monitor name that
# does gets a basic string with the two escapes that form needs instead.
toml_string() {
    local value="$1"

    case "$value" in
        *"'"*)
            value="${value//\\/\\\\}"
            value="${value//\"/\\\"}"
            printf '"%s"' "$value"
            ;;
        *)
            printf "'%s'" "$value"
            ;;
    esac
}

# Fallback patterns AeroSpace understands on any Mac, used when a role has no
# monitor name configured - and appended after the name when it does, so an
# unplugged display sends its workspaces somewhere real instead of nowhere.
role_monitor_patterns() {
    local role="$1"
    local name

    name="$(aerospace_layout_monitor_name_for_role "$role")"
    [ -z "$name" ] || printf '%s\n' "$(toml_string "$name")"

    case "$role" in
        main)
            printf "'main'\n"
            ;;
        side)
            printf "'secondary'\n"
            printf "'main'\n"
            ;;
        stage)
            printf "'built-in'\n"
            printf "'secondary'\n"
            printf "'main'\n"
            ;;
    esac
}

generate_layout_block() {
    local workspace role pattern first

    printf 'persistent-workspaces = ['
    first=1
    for workspace in $(aerospace_layout_workspaces); do
        if [ "$first" -eq 1 ]; then
            first=0
        else
            printf ', '
        fi
        printf "%s" "$(toml_string "$workspace")"
    done
    printf ']\n'
    printf '\n'

    printf '[workspace-to-monitor-force-assignment]\n'
    for role in $(aerospace_layout_roles); do
        for workspace in $(aerospace_layout_workspaces_for_role "$role"); do
            printf '    %s = [' "$(toml_string "$workspace")"
            first=1
            while IFS= read -r pattern; do
                [ -n "$pattern" ] || continue
                if [ "$first" -eq 1 ]; then
                    first=0
                else
                    printf ', '
                fi
                printf '%s' "$pattern"
            done <<EOF
$(role_monitor_patterns "$role")
EOF
            printf ']\n'
        done
    done
}

generate_keys_block() {
    local workspace key index=0 unbound=0
    local -a keys
    local refresh_command

    refresh_command='exec-and-forget /bin/bash $HOME/.config/sketchybar/plugins/aerospace_spaces_refresh.sh'

    keys=()
    for key in $AEROSPACE_LAYOUT_WORKSPACE_KEYS; do
        keys[${#keys[@]}]="$key"
    done

    for workspace in $(aerospace_layout_workspaces); do
        if [ "$index" -ge "${#keys[@]}" ]; then
            unbound=$((unbound + 1))
            continue
        fi
        printf "    ctrl-%s = 'workspace %s'\n" "${keys[$index]}" "$workspace"
        index=$((index + 1))
    done

    printf '\n'

    index=0
    for workspace in $(aerospace_layout_workspaces); do
        if [ "$index" -ge "${#keys[@]}" ]; then
            continue
        fi
        printf "    ctrl-shift-%s = ['move-node-to-workspace --focus-follows-window %s', '%s']\n" \
            "${keys[$index]}" "$workspace" "$refresh_command"
        index=$((index + 1))
    done

    if [ "$unbound" -gt 0 ]; then
        printf '    # %s workspace(s) past this point have no single-key shortcut.\n' "$unbound"
        printf '    # Reach them with Ctrl+Left / Ctrl+Right.\n'
    fi
}

has_marker() {
    /usr/bin/grep -Fxq "$1" "$config_path"
}

replace_block() {
    local source_file="$1"
    local begin="$2"
    local end="$3"
    local payload_file="$4"

    /usr/bin/awk -v begin="$begin" -v end="$end" -v payload="$payload_file" '
        $0 == begin {
            print
            while ((getline line < payload) > 0) {
                print line
            }
            close(payload)
            inside = 1
            next
        }
        $0 == end {
            print
            inside = 0
            next
        }
        !inside { print }
    ' "$source_file"
}

for marker in "$LAYOUT_BEGIN" "$LAYOUT_END" "$KEYS_BEGIN" "$KEYS_END"; do
    if ! has_marker "$marker"; then
        printf 'Missing generated-block marker in %s:\n  %s\n' "$config_path" "$marker" >&2
        printf 'Redeploy the shipped config (bootstrap/install/aerospace.sh --deploy-only) or add the\n' >&2
        printf 'marker pair back by hand; this script only rewrites what is between markers.\n' >&2
        exit 1
    fi
done

work_dir="$(mktemp -d)"
trap 'rm -rf "$work_dir"' EXIT

layout_payload="$work_dir/layout.toml"
keys_payload="$work_dir/keys.toml"
staged="$work_dir/staged.toml"

generate_layout_block >"$layout_payload"
generate_keys_block >"$keys_payload"

replace_block "$config_path" "$LAYOUT_BEGIN" "$LAYOUT_END" "$layout_payload" >"$work_dir/step1.toml"
replace_block "$work_dir/step1.toml" "$KEYS_BEGIN" "$KEYS_END" "$keys_payload" >"$staged"

# tomllib ships with python 3.11+. Where it is missing the render still happens;
# refusing to write a valid file because the validator is old would be worse
# than not validating.
if command -v python3 >/dev/null 2>&1; then
    if python3 -c 'import tomllib' >/dev/null 2>&1; then
        if ! python3 -c 'import pathlib, sys, tomllib; tomllib.loads(pathlib.Path(sys.argv[1]).read_text())' "$staged"; then
            printf 'Generated config is not valid TOML; %s was left alone.\n' "$config_path" >&2
            exit 1
        fi
    fi
fi

# App placement rules name workspaces too, and lib/layout.sh maps the ones a
# shrunken workspace list no longer has onto ones it does. Re-rendering them
# here is what keeps "edit workspaces.conf, run one command" true, and it is a
# no-op whenever the app rules already match.
render_app_rules_if_wanted() {
    [ "$render_app_rules" -eq 1 ] || return 0
    [ -x "$SCRIPT_DIR/render-app-rules.sh" ] || return 0

    if ! "$SCRIPT_DIR/render-app-rules.sh" "$config_path"; then
        printf 'App placement rules could not be re-rendered; %s still has the previous ones.\n' \
            "$config_path" >&2
    fi
}

if /usr/bin/cmp -s "$staged" "$config_path"; then
    if [ "$check_only" -eq 1 ]; then
        printf 'Up to date: %s matches workspaces.conf and displays.conf.\n' "$config_path"
        exit 0
    fi

    printf 'Unchanged: %s\n' "$config_path"
    render_app_rules_if_wanted
    exit 0
fi

if [ "$check_only" -eq 1 ]; then
    printf 'Out of date: %s does not match workspaces.conf and displays.conf.\n' "$config_path" >&2
    /usr/bin/diff -u "$config_path" "$staged" | /usr/bin/head -n 40 >&2 || true
    printf 'Run %s to regenerate it.\n' "$SCRIPT_DIR/render-layout.sh" >&2
    exit 1
fi

stamp="$(date +%Y%m%d-%H%M%S)"
cp "$config_path" "$config_path.bak-$stamp-render-layout"
cp "$staged" "$config_path"

printf 'Rendered %s from workspaces.conf and displays.conf (%s workspace(s)).\n' \
    "$config_path" "$(aerospace_layout_workspace_count)"
printf 'Previous file kept at %s\n' "$config_path.bak-$stamp-render-layout"

render_app_rules_if_wanted
